apiVersion: kagent.dev/v1alpha2
kind: RemoteMCPServer
metadata:
  name: fortigate-mcp-remote
  namespace: kagent
spec:
  description: FortiGate MCP Server - Manage FortiGate firewall policies, addresses, services, routes, and VIPs
  url: http://fortigate-mcp-server.kagent.svc.cluster.local:8082/mcp
  protocol: STREAMABLE_HTTP
  timeout: 30s
  terminateOnClose: false
